export default {
  name: 'animecharacter',
  description: 'Find out which anime character represents you!',
  async execute(message) {
    const characters = [
      { name: 'Naruto Uzumaki', anime: 'Naruto', traits: 'Energetic, determined, and full of heart.', image: 'https://i.imgur.com/1nBd9ml.jpg' },
      { name: 'Levi Ackerman', anime: 'Attack on Titan', traits: 'Calm, deadly, and always cleans up.', image: 'https://i.imgur.com/VWlOHsB.jpg' },
      { name: 'Gojo Satoru', anime: 'Jujutsu Kaisen', traits: 'Stylish, powerful, and a bit of a show-off.', image: 'https://i.imgur.com/8lv8FNs.jpg' },
      { name: 'Hinata Hyuga', anime: 'Naruto', traits: 'Shy but strong, and fiercely loyal.', image: 'https://i.imgur.com/C59NRvU.jpg' },
      { name: 'Luffy', anime: 'One Piece', traits: 'Carefree, fearless, and always hungry.', image: 'https://i.imgur.com/gTgZ7dV.jpg' },
      { name: 'Light Yagami', anime: 'Death Note', traits: 'Smart, intense, and morally... questionable.', image: 'https://i.imgur.com/Z2He8Uh.jpg' },
      { name: 'Saitama', anime: 'One Punch Man', traits: 'Overpowered and bored, but a hero at heart.', image: 'https://i.imgur.com/HX1TKlw.jpg' },
      { name: 'Edward Elric', anime: 'Fullmetal Alchemist', traits: 'Determined, passionate, and stubborn.', image: 'https://i.imgur.com/W0h7Jw7.jpg' },
      { name: 'Mikasa Ackerman', anime: 'Attack on Titan', traits: 'Protective, skilled, and loyal to a fault.', image: 'https://i.imgur.com/w5QqZyE.jpg' },
      { name: 'Tanjiro Kamado', anime: 'Demon Slayer', traits: 'Kind-hearted, hardworking, and brave.', image: 'https://i.imgur.com/nlVaJyx.jpg' },
      { name: 'Zero Two', anime: 'Darling in the Franxx', traits: 'Mysterious, playful, and intense.', image: 'https://i.imgur.com/EvssB2k.jpg' },
      { name: 'Kaguya Shinomiya', anime: 'Kaguya-sama: Love Is War', traits: 'Proud, intelligent, and tsundere.', image: 'https://i.imgur.com/XpJcm61.jpg' },
      { name: 'Eren Yeager', anime: 'Attack on Titan', traits: 'Fierce, determined, and unyielding.', image: 'https://i.imgur.com/LMKcLQz.jpg' },
      { name: 'Roronoa Zoro', anime: 'One Piece', traits: 'Loyal, strong, and a swordsman with a nose for direction (or lack thereof).', image: 'https://i.imgur.com/hVfQoR9.jpg' },
      { name: 'Kakashi Hatake', anime: 'Naruto', traits: 'Laid-back, brilliant, and mysterious.', image: 'https://i.imgur.com/Vo6G8rc.jpg' },
      { name: 'Natsu Dragneel', anime: 'Fairy Tail', traits: 'Fiery, impulsive, and fiercely loyal.', image: 'https://i.imgur.com/1UpC8pn.jpg' },
      { name: 'Shoto Todoroki', anime: 'My Hero Academia', traits: 'Calm, conflicted, and powerful.', image: 'https://i.imgur.com/MXrghmS.jpg' },
      { name: 'Megumin', anime: 'Konosuba', traits: 'Energetic, explosive, and a bit eccentric.', image: 'https://i.imgur.com/R2fJ4Rt.jpg' },
      { name: 'Ichigo Kurosaki', anime: 'Bleach', traits: 'Protective, stubborn, and courageous.', image: 'https://i.imgur.com/YHtg5Zc.jpg' },
      { name: 'Sasuke Uchiha', anime: 'Naruto', traits: 'Brooding, skilled, and revenge-driven.', image: 'https://i.imgur.com/VZKqIlt.jpg' },
      { name: 'Yuno Gasai', anime: 'Future Diary', traits: 'Obsessive, protective, and unhinged.', image: 'https://i.imgur.com/5Ogud7j.jpg' },
      { name: 'Sakura Haruno', anime: 'Naruto', traits: 'Determined, strong-willed, and compassionate.', image: 'https://i.imgur.com/fRkLZXP.jpg' },
      { name: 'Spike Spiegel', anime: 'Cowboy Bebop', traits: 'Cool, laid-back, and skilled.', image: 'https://i.imgur.com/GjSjAqF.jpg' },
      { name: 'Rei Ayanami', anime: 'Neon Genesis Evangelion', traits: 'Quiet, mysterious, and complex.', image: 'https://i.imgur.com/MuXykIk.jpg' },
      { name: 'Vash the Stampede', anime: 'Trigun', traits: 'Kind-hearted, goofy, and deadly.', image: 'https://i.imgur.com/BXGYQ6A.jpg' },
      { name: 'Alphonse Elric', anime: 'Fullmetal Alchemist', traits: 'Gentle, loyal, and brave.', image: 'https://i.imgur.com/T9MLTHT.jpg' },
      { name: 'Rintarou Okabe', anime: 'Steins;Gate', traits: 'Eccentric, clever, and passionate.', image: 'https://i.imgur.com/LDtqkR0.jpg' },
      { name: 'Goku', anime: 'Dragon Ball Z', traits: 'Cheerful, powerful, and endlessly determined.', image: 'https://i.imgur.com/Xq0Rzyv.jpg' },
      { name: 'Hinagiku Katsura', anime: 'Hayate no Gotoku!', traits: 'Strong, caring, and a bit tsundere.', image: 'https://i.imgur.com/ljq0N75.jpg' },
      { name: 'Ken Kaneki', anime: 'Tokyo Ghoul', traits: 'Conflicted, determined, and compassionate.', image: 'https://i.imgur.com/7wZ6MkS.jpg' },
      { name: 'Nico Robin', anime: 'One Piece', traits: 'Calm, intelligent, and mysterious.', image: 'https://i.imgur.com/yxRZ7uW.jpg' },
      { name: 'Kenshin Himura', anime: 'Rurouni Kenshin', traits: 'Gentle, skilled swordsman, with a dark past.', image: 'https://i.imgur.com/E8x4iUb.jpg' },
      { name: 'Rukia Kuchiki', anime: 'Bleach', traits: 'Serious, caring, and brave.', image: 'https://i.imgur.com/UXYTVg1.jpg' },
      { name: 'Maka Albarn', anime: 'Soul Eater', traits: 'Strong-willed, brave, and loyal.', image: 'https://i.imgur.com/zR9SvQe.jpg' },
      { name: 'Yusuke Urameshi', anime: 'Yu Yu Hakusho', traits: 'Rebellious, strong, and kind-hearted.', image: 'https://i.imgur.com/Mn7F8fl.jpg' },
      { name: 'Izuku Midoriya', anime: 'My Hero Academia', traits: 'Determined, smart, and kind.', image: 'https://i.imgur.com/Y7Uz6lN.jpg' },
      { name: 'Rem', anime: 'Re:Zero', traits: 'Loyal, kind, and powerful.', image: 'https://i.imgur.com/rQNzQtU.jpg' },
      { name: 'Zero Two', anime: 'Darling in the Franxx', traits: 'Mysterious, playful, and intense.', image: 'https://i.imgur.com/EvssB2k.jpg' },
      { name: 'Tomoya Okazaki', anime: 'Clannad', traits: 'Kind, caring, and a bit rebellious.', image: 'https://i.imgur.com/jxh4uEf.jpg' },
      { name: 'Makoto Naegi', anime: 'Danganronpa', traits: 'Optimistic, lucky, and determined.', image: 'https://i.imgur.com/4HsyVnV.jpg' },
      { name: 'Yoko Littner', anime: 'Gurren Lagann', traits: 'Bold, confident, and fiery.', image: 'https://i.imgur.com/djs7WpO.jpg' },
      { name: 'Erza Scarlet', anime: 'Fairy Tail', traits: 'Strong, disciplined, and caring.', image: 'https://i.imgur.com/VjNHNVe.jpg' },
      { name: 'Killua Zoldyck', anime: 'Hunter x Hunter', traits: 'Cool, skilled, and loyal.', image: 'https://i.imgur.com/U0CJoMZ.jpg' },
      { name: 'Gintoki Sakata', anime: 'Gintama', traits: 'Lazy, funny, but serious when needed.', image: 'https://i.imgur.com/TvztDVP.jpg' },
      { name: 'Raven', anime: 'Teen Titans (anime-inspired)', traits: 'Mysterious, reserved, and powerful.', image: 'https://i.imgur.com/qwo1Qmz.jpg' },
      { name: 'Yuno Gasai', anime: 'Future Diary', traits: 'Obsessive, protective, and unhinged.', image: 'https://i.imgur.com/5Ogud7j.jpg' },
      { name: 'Tsuyu Asui', anime: 'My Hero Academia', traits: 'Calm, straightforward, and reliable.', image: 'https://i.imgur.com/kpBivGU.jpg' },
      { name: 'Roronoa Zoro', anime: 'One Piece', traits: 'Loyal, strong, and a swordsman with a nose for direction (or lack thereof).', image: 'https://i.imgur.com/hVfQoR9.jpg' },
      { name: 'Holo', anime: 'Spice and Wolf', traits: 'Wise, playful, and a bit mischievous.', image: 'https://i.imgur.com/3JkqSnQ.jpg' },
      { name: 'Saber', anime: 'Fate/stay night', traits: 'Noble, skilled warrior with a strong sense of honor.', image: 'https://i.imgur.com/fqzTeVh.jpg' },
      { name: 'Inuyasha', anime: 'Inuyasha', traits: 'Brash, strong, and caring.', image: 'https://i.imgur.com/4Y2PZMY.jpg' },
      { name: 'Shinji Ikari', anime: 'Neon Genesis Evangelion', traits: 'Reluctant, complicated, and sensitive.', image: 'https://i.imgur.com/MuXykIk.jpg' },
      { name: 'Misaki Ayuzawa', anime: 'Maid Sama!', traits: 'Strong, caring, and disciplined.', image: 'https://i.imgur.com/dB4Z9Z9.jpg' },
      { name: 'Yuuko Ichihara', anime: 'xxxHolic', traits: 'Mysterious, wise, and enigmatic.', image: 'https://i.imgur.com/bKlB0OQ.jpg' },
      { name: 'Shoyo Hinata', anime: 'Haikyuu!!', traits: 'Energetic, passionate, and determined.', image: 'https://i.imgur.com/zsdZWhC.jpg' },
      { name: 'Kallen Kozuki', anime: 'Code Geass', traits: 'Fiery, passionate, and a strong pilot.', image: 'https://i.imgur.com/56ohxI1.jpg' },
      { name: 'Senku Ishigami', anime: 'Dr. Stone', traits: 'Genius, resourceful, and curious.', image: 'https://i.imgur.com/8IXBt1d.jpg' },
      { name: 'Yuri Katsuki', anime: 'Yuri on Ice', traits: 'Sensitive, determined, and kind.', image: 'https://i.imgur.com/cZbX2bH.jpg' },
      { name: 'Kousei Arima', anime: 'Your Lie in April', traits: 'Talented, emotional, and kind.', image: 'https://i.imgur.com/6LHOhYx.jpg' },
      { name: 'Rikka Takanashi', anime: 'Love, Chunibyo & Other Delusions', traits: 'Imaginative, quirky, and determined.', image: 'https://i.imgur.com/kZzDnW6.jpg' },
      { name: 'Misato Katsuragi', anime: 'Neon Genesis Evangelion', traits: 'Confident, caring, and strong.', image: 'https://i.imgur.com/R0y8n15.jpg' },
      { name: 'Nana Osaki', anime: 'Nana', traits: 'Strong, independent, and passionate.', image: 'https://i.imgur.com/w0hYqdr.jpg' },
      { name: 'Nanami Kento', anime: 'Jujutsu Kaisen', traits: 'Serious, calm, and reliable.', image: 'https://i.imgur.com/GkUPbtQ.jpg' },
      { name: 'Shoto Todoroki', anime: 'My Hero Academia', traits: 'Calm, conflicted, and powerful.', image: 'https://i.imgur.com/MXrghmS.jpg' },
      { name: 'Zenitsu Agatsuma', anime: 'Demon Slayer', traits: 'Cowardly but brave when needed.', image: 'https://i.imgur.com/gURe7iL.jpg' },
      { name: 'Inosuke Hashibira', anime: 'Demon Slayer', traits: 'Wild, loud, and passionate.', image: 'https://i.imgur.com/4Xz3b9h.jpg' },
      { name: 'Guts', anime: 'Berserk', traits: 'Relentless, fierce, and strong.', image: 'https://i.imgur.com/s7HHoZy.jpg' },
      { name: 'Shigeo "Mob" Kageyama', anime: 'Mob Psycho 100', traits: 'Quiet, kind, with overwhelming psychic power.', image: 'https://i.imgur.com/B4MdB4c.jpg' },
      { name: 'Makunouchi Ippo', anime: 'Hajime no Ippo', traits: 'Hardworking, kind, and determined boxer.', image: 'https://i.imgur.com/GqHj3TC.jpg' },
      { name: 'Rimuru Tempest', anime: 'That Time I Got Reincarnated as a Slime', traits: 'Adaptable, intelligent, and caring.', image: 'https://i.imgur.com/L28az7v.jpg' },
      { name: 'Karma Akabane', anime: 'Assassination Classroom', traits: 'Cunning, mischievous, and highly skilled.', image: 'https://i.imgur.com/bv2kZRx.jpg' },
      { name: 'Sosuke Aizen', anime: 'Bleach', traits: 'Manipulative, intelligent, and powerful villain.', image: 'https://i.imgur.com/QNuJe9L.jpg' },
      { name: 'Medaka Kurokami', anime: 'Medaka Box', traits: 'Perfect, charismatic, and skilled.', image: 'https://i.imgur.com/7wp3ejE.jpg' },
      { name: 'Tomura Shigaraki', anime: 'My Hero Academia', traits: 'Chaotic, powerful villain with dark goals.', image: 'https://i.imgur.com/3x1J4TQ.jpg' },
      { name: 'Yagami Light', anime: 'Death Note', traits: 'Intelligent, manipulative, and morally complex.', image: 'https://i.imgur.com/Z2He8Uh.jpg' },
      { name: 'Raven', anime: 'Teen Titans (anime-inspired)', traits: 'Mysterious, reserved, and powerful.', image: 'https://i.imgur.com/qwo1Qmz.jpg' },
      { name: 'Gohan', anime: 'Dragon Ball Z', traits: 'Gentle, strong, and studious.', image: 'https://i.imgur.com/v3mHXvW.jpg' },
      { name: 'Kuroko Tetsuya', anime: 'Kuroko no Basket', traits: 'Quiet, determined, and unassuming.', image: 'https://i.imgur.com/rdH4cGB.jpg' },
      { name: 'Yuki Nagato', anime: 'The Melancholy of Haruhi Suzumiya', traits: 'Calm, intelligent, and mysterious.', image: 'https://i.imgur.com/etUb6Ut.jpg' },
      { name: 'Satsuki Kiryuin', anime: 'Kill la Kill', traits: 'Commanding, confident, and ambitious.', image: 'https://i.imgur.com/W4nJkFt.jpg' },
      { name: 'Rukako Urushibara', anime: 'Steins;Gate', traits: 'Gentle, kind, and shy.', image: 'https://i.imgur.com/0urD0Md.jpg' },
      { name: 'Joseph Joestar', anime: 'JoJo\'s Bizarre Adventure', traits: 'Clever, humorous, and resourceful.', image: 'https://i.imgur.com/cq2Nj9Y.jpg' },
      { name: 'Dio Brando', anime: 'JoJo\'s Bizarre Adventure', traits: 'Charismatic, evil, and powerful.', image: 'https://i.imgur.com/8vyrxNz.jpg' },
      { name: 'Jotaro Kujo', anime: 'JoJo\'s Bizarre Adventure', traits: 'Stoic, cool-headed, and powerful.', image: 'https://i.imgur.com/kp3PoX7.jpg' },
      { name: 'Kaguya Otsutsuki', anime: 'Naruto', traits: 'God-like power, cold, and ruthless.', image: 'https://i.imgur.com/9TPv5Jo.jpg' },
      { name: 'Akame', anime: 'Akame ga Kill!', traits: 'Silent, deadly, and determined.', image: 'https://i.imgur.com/fdV7U7T.jpg' },
      { name: 'Saitama', anime: 'One Punch Man', traits: 'Overpowered and bored, but a hero at heart.', image: 'https://i.imgur.com/HX1TKlw.jpg' },
      { name: 'Senjougahara Hitagi', anime: 'Monogatari', traits: 'Sharp, witty, and complex.', image: 'https://i.imgur.com/dJsmDHQ.jpg' },
      { name: 'Hachiman Hikigaya', anime: 'My Teen Romantic Comedy', traits: 'Cynical, intelligent, and isolated.', image: 'https://i.imgur.com/3XtF0Rz.jpg' },
      { name: 'Kagome Higurashi', anime: 'Inuyasha', traits: 'Kind, determined, and strong-willed.', image: 'https://i.imgur.com/7FzH7jE.jpg' },
      { name: 'Yuki Sohma', anime: 'Fruits Basket', traits: 'Gentle, kind, and loyal.', image: 'https://i.imgur.com/7ylYbGc.jpg' },
      { name: 'Haruhi Fujioka', anime: 'Ouran High School Host Club', traits: 'Smart, down-to-earth, and kind.', image: 'https://i.imgur.com/ZZIlzRG.jpg' },
      { name: 'Shiro', anime: 'No Game No Life', traits: 'Genius, quiet, and competitive.', image: 'https://i.imgur.com/r6iK8sp.jpg' },
      { name: 'Ryuko Matoi', anime: 'Kill la Kill', traits: 'Fiery, determined, and fierce.', image: 'https://i.imgur.com/1XABXqP.jpg' },
      { name: 'Ichigo Kurosaki', anime: 'Bleach', traits: 'Protective, stubborn, and courageous.', image: 'https://i.imgur.com/YHtg5Zc.jpg' },
      { name: 'Zero Two', anime: 'Darling in the Franxx', traits: 'Mysterious, playful, and intense.', image: 'https://i.imgur.com/EvssB2k.jpg' },
      { name: 'Megumin', anime: 'Konosuba', traits: 'Energetic, explosive, and a bit eccentric.', image: 'https://i.imgur.com/R2fJ4Rt.jpg' },
      { name: 'Yato', anime: 'Noragami', traits: 'Funny, arrogant, but kind-hearted god.', image: 'https://i.imgur.com/0mgHTly.jpg' },
      { name: 'Gon Freecss', anime: 'Hunter x Hunter', traits: 'Optimistic, curious, and strong-willed.', image: 'https://i.imgur.com/GTq9d0B.jpg' }
    ];

    const random = characters[Math.floor(Math.random() * characters.length)];

    const embed = {
      color: 0x0099ff,
      title: `🧠 You are ${random.name}!`,
      description: `From *${random.anime}*\n\n**Traits:** ${random.traits}`,
      image: {
        url: random.image
      },
      footer: {
        text: `Requested by ${message.author.tag}`,
        icon_url: message.author.displayAvatarURL()
      }
    };

    await message.channel.send({ embeds: [embed] });
  }
};
